ApiTest/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('accounts/login/', user_login, name='login'),
    path('accounts/logout/', user_logout, name='logout'),
    
    path('', index, name='index'),

    path('project/', prj_list, name='prj_list'),
    path('project/add/', prj_add, name='prj_add'),
    path('project/update/<int:prj_id>/', prj_update, name='prj_update'),
    path('project/del/<int:prj_id>/', prj_del, name='prj_del'),

    path('env/', env_list, name='env_list'),
    path('env/add/', env_add, name='env_add'),
    path('env/update/<int:env_id>/', env_update, name='env_update'),
    path('env/del/<int:env_id>/', env_del, name='env_del'),

    path('prj_env/', prj_env_list, name='prj_env_list'),
    path('prj_env/add/', prj_env_add, name='prj_env_add'),
    path('prj_env/update/<int:prj_env_id>/', prj_env_update, name='prj_env_update'),
    path('prj_env/del/<int:prj_env_id>/', prj_env_del, name='prj_env_del'),

    path('api/', api_list, name='api_list'),
    path('api/add/', api_add, name='api_add'),
    path('api/update/<int:api_id>/', api_update, name='api_update'),
    path('api/test/', api_test, name='api_test'),
    path('api/test/<int:api_id>/', api_test, name='api_test'),
    path('api/del/<int:api_id>/', api_del, name='api_del'),
    path('api_of_project/', api_of_project, name='api_of_project'),

    path('save_steps/', save_steps, name='save_steps'),

    path('case/', case_list, name='case_list'),
    path('case/add/', case_add, name='case_add'),
    path('case/update/<int:case_id>/', case_update, name='case_update'),
    path('case/del/<int:case_id>/', case_del, name='case_del'),

    path('plan/', plan_list, name='plan_list'),
    path('plan/add/', plan_add, name='plan_add'),
    path('plan/update/<int:plan_id>/', plan_update, name='plan_update'),
    path('plan/run/', plan_run, name='plan_run'),
    path('plan/del/<int:plan_id>/', plan_report, name='plan_report'),
    path('plan/del/<int:plan_id>/', plan_del, name='plan_del'),

    path('report/', report_list, name='report_list'),
    path('report/detail/<int:report_id>/', report_detail, name='report_detail'),
    path('report/del/<int:report_id>/', report_del, name='report_del'),

    path('sign/', sign_list, name='sign_list'),
    path('sign/detail/<int:sign_id>/', sign_detail, name='sign_detail'),
    path('sign/del/<int:sign_id>/', sign_del, name='sign_del'),


]

app/models.py
from django.db import models


class Sign(models.Model):
    name = models.CharField('名称', max_length=50)
    description = models.CharField('描述', max_length=100, blank=True, null=True)
    content = models.TextField('内容', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:  
        verbose_name = '签名设置'  
        verbose_name_plural = '签名设置' 


class Project(models.Model):
    name = models.CharField('名称', max_length=50)
    developer = models.CharField('开发负责人', max_length=50, blank=True, null=True)
    description = models.CharField('描述', max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.name

    class Meta:  
        verbose_name = '项目管理'  
        verbose_name_plural = '项目管理' 


class Environment(models.Model):
    name = models.CharField('名称', max_length=50)
    description = models.CharField('描述', max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.name

    class Meta:  
        verbose_name = '环境设置'  
        verbose_name_plural = '环境设置' 


class ProjectEnv(models.Model):
    env = models.ForeignKey('Environment', on_delete=models.CASCADE, verbose_name='环境')
    project = models.ForeignKey('Project', on_delete=models.CASCADE, verbose_name='项目')
    url = models.CharField('Url地址', max_length=100)
    sign = models.ForeignKey('Sign', on_delete=models.CASCADE, blank=True, null=True, verbose_name='签名')
    access_id = models.CharField('AccessID',max_length=50, blank=True, null=True)
    access_key = models.CharField('AccessKey',max_length=50, blank=True, null=True)
    
    def __str__(self):
        return self.project.name

    class Meta:  
        verbose_name = '项目设置'  
        verbose_name_plural = '项目设置'
    

class Api(models.Model):
    METHOD = ((1, "POST"), (2, "GET"))
    DATA_TYPE = ((1, "JSON"), (2, "FORM"))
    
    name = models.CharField('名称', max_length=50)
    description = models.CharField('描述', max_length=100, blank=True, null=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, verbose_name='项目') 
    url = models.CharField('Url地址', max_length=100)
    method = models.IntegerField('请求方法', choices=METHOD)
    data_type = models.IntegerField('数据类型', choices=DATA_TYPE)
    request_body = models.TextField('请求数据', blank=True, null=True)
    response_body = models.TextField('响应数据', blank=True, null=True)
    
    def __str__(self):
        return self.name

    class Meta:  
        verbose_name = '接口管理'  
        verbose_name_plural = '接口管理' 


class Step(models.Model):
    sn = models.IntegerField('序号', blank=True, null=True)
    case = models.ForeignKey('TestCase', on_delete=models.CASCADE, verbose_name='用例')
    api = models.ForeignKey('Api', on_delete=models.CASCADE, verbose_name='接口')
    data = models.TextField('数据', blank=True, null=True)
    assertion = models.TextField('断言', blank=True, null=True)
    

    def __str__(self):
        return self.case.name

    class Meta:  
        verbose_name = '步骤管理'  
        verbose_name_plural = '步骤管理' 

    
class TestCase(models.Model):
    name = models.CharField('名称', max_length=50, blank=True, null=True)
    description = models.CharField('描述', max_length=100, blank=True, null=True)
    plan = models.ForeignKey('TestPlan', on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return self.name

    class Meta:  
        verbose_name = '测试用例'  
        verbose_name_plural = '测试用例'


class TestPlan(models.Model):
    name = models.CharField('名称', max_length=50)
    environment = models.ForeignKey('Environment', on_delete=models.CASCADE, verbose_name='环境')
    description = models.CharField('描述', max_length=100, blank=True, null=True)
    
    def __str__(self):
        return self.name

    class Meta:  
        verbose_name = '测试计划'  
        verbose_name_plural = '测试计划'


class TestReport(models.Model):
    test_plan = models.ForeignKey('TestPlan', on_delete=models.CASCADE)
    content = models.TextField('内容', blank=True, null=True)
    case_num = models.IntegerField('用例数量', blank=True, null=True)
    pass_num = models.IntegerField('通过数量', blank=True, null=True)
    fail_num = models.IntegerField('失败数量', blank=True, null=True)
    error_num = models.IntegerField('出错数量', blank=True, null=True)
    
    def __str__(self):
        return self.name
    
    class Meta:  
        verbose_name = '测试报告'  
        verbose_name_plural = '测试报告'

class StepResult(models.Model):
    # STATUS = ((1, "PASS"), (2, "FAIL"), (3, "SKIP"), (4, "ERROR"))
    test_case_result = models.ForeignKey('TestCaseResult', on_delete=models.CASCADE, verbose_name='测试用例结果')
    step = models.ForeignKey('Step', on_delete=models.CASCADE, verbose_name='步骤')
    api_name = models.CharField('接口名称', max_length=100, blank=True, null=True)
    api_url = models.CharField('接口Url', max_length=100, blank=True, null=True)
    api_data = models.CharField('请求数据', max_length=100, blank=True, null=True)
    api_response = models.CharField('响应内容', max_length=100, blank=True, null=True)
    status = models.CharField('状态', max_length=10, blank=True, null=True)
    
    def __str__(self):
        return self.step.case.name

    class Meta:  
        verbose_name = '步骤结果'  
        verbose_name_plural = '步骤结果'

    
class TestCaseResult(models.Model):
    # STATUS = ((1, "PASS"), (2, "FAIL"), (3, "SKIP"), (4, "ERROR"))
    report = models.ForeignKey('TestReport', on_delete=models.CASCADE, verbose_name='测试报告')
    case = models.ForeignKey('TestCase', on_delete=models.CASCADE, verbose_name='测试用例')
    status = models.CharField('状态', max_length=10, blank=True, null=True)
    
    def __str__(self):
        return self.case.name

    class Meta:  
        verbose_name = '用例结果'  
        verbose_name_plural = '用例结果'

app/templates/api_add.html
{% extends "base.html" %}
{% block title %}添加接口{% endblock %}
{% block content %}
	<div class="row">
		<ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">主页</a></li>
		  <li><a href="{% url 'api_list' %}">接口</a></li>
		  <li>添加接口</li>
		</ol>
	</div>
	<div class="row">
		<div class="col-md-12">
			<!-- INPUTS -->
			<div class="panel">
				<div class="panel-heading">
					<h3 class="panel-title">添加接口</h3>
				</div>
				<div class="panel-body">
					<form name='api_detail_form' id='api_detail_form' class="form-horizontal" action='.' method="POST" >
						{% csrf_token %}

						<div class="form-group">
							<label for="name" class="col-sm-2 control-label">接口名称</label>
							<div class="col-sm-10">
								<div class="input-group">
									<input id="name" name="name" type="text" class="form-control" value="">
									<span class="input-group-btn">
								    	<button class="btn btn-default" data-toggle="modal" data-target="#testModal" type="button">测试</button>
								    </span>
                                    <div id="testModal" class="modal fade" tabindex="-1" role="dialog">
                                      <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">测试接口</h4>
                                          </div>
                                          <div class="modal-body">
                                            <div class="form-group">
												<label for="prj_id" class="col-sm-2 control-label">选择环境</label>
												<div class="col-sm-10">
													<select name="env_id" class="form-control">
														{% for env in env_list %}
														<option value="{{env.id}}">{{env.name}}</option>
														{% endfor %}
													</select>
												</div>
											</div>
											<pre id='test_response'>--- 响应结果 ---</pre>
                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" onclick="testAction()">发送</button>
                                          </div>
                                        </div><!-- /.modal-content -->
                                      </div><!-- /.modal-dialog -->
                                    </div><!-- /.modal -->
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="description" class="col-sm-2 control-label">接口描述</label>
							<div class="col-sm-10">
								<textarea id="description" name="description" class="form-control" rows="3" style="resize: none;"></textarea>
							</div>
						</div>
						<div class="form-group">
							<label for="prj_id" class="col-sm-2 control-label">项目名称</label>
							<div class="col-sm-10">
								<select name="prj_id" class="form-control">
									{% for prj in prj_list %}
									<option value="{{prj.id}}">{{prj.name}}</option>
									{% endfor %}
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="url" class="col-sm-2 control-label">接口Url</label>
							<div class="col-sm-8" style="padding-right: 0">
								<input id="url" name="url" type="text" class="form-control" value="">
							</div>
							<div class="col-sm-2" style="padding-left: 0">
						      	<select name="method" class="form-control">
						      		<option value="1" selected="selected">POST</option>
						      		<option value="2">GET</option>
						      	</select>
							</div>
						</div>
						<div class="form-group form-inline">
							<label for="data_type" class="col-sm-2 control-label">数据类型</label>
							<div class="col-sm-10">
								<label style="padding-right: 20px">
									<input name="data_type" value="1" checked="checked"type="radio">
									<span>JSON</span>
								</label>
								<label style="padding-right: 20px">
									<input name="data_type" value="2" type="radio">
									<span>FORM</span>
								</label>
							</div>
						</div>
						<div class="form-group">
							<label for="request_body" class="col-sm-2 control-label">请求数据</label>
							<div class="col-sm-10">
								<textarea id="request_body" name="request_body" class="form-control" rows="5"></textarea>
							</div>
						</div>
						<div class="form-group">
							<label for="request_body" class="col-sm-2 control-label">响应数据</label>
							<div class="col-sm-10">
								<textarea id="request_body" name="response_body" class="form-control" rows="5"></textarea>
							</div>
						</div>
						<div class="form-group form-inline">
						    <div class="col-sm-offset-2 col-sm-10">
							    <button type="submit" class="btn btn-default">保存</button>
						    </div>
						</div>
					</form>
				</div>
			</div>
			<!-- END INPUTS -->
		</div>
	</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	function testAction(){
	    $.ajax({
            type: "POST",
            url: "{% url 'api_test' %}" ,
            data: $('#api_detail_form').serialize(),
            success: function (result) {
            	$("#test_response").html(result);
            },
            error : function() {
                console.log(result);
            }
        });
	}
</script>
{% endblock %}

app/templates/api_list.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
	<div class="row">
		<ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">主页</a></li>
		  <li>接口</li>
		</ol>
	</div>
	<div class="row">
		<div class="col-md-12">
			<!-- BORDERED TABLE -->
			<div class="panel">
				<div class="panel-body">
					<form style="padding: 10px 0; ">
						<a href="{% url 'api_add' %}"><button type="button" class="btn btn-primary">添加接口</button></a>
					</form>
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>接口名称</th>
								<th>项目名称</th>
								<th>接口地址</th>
								<th>请求方法</th>
								<th>数据类型</th>
								<th>接口描述</th>
								<th>操作</th>
							</tr>
						</thead>
						<tbody>
							{% for api in api_list %}
							<tr>
								<td>{{api.id}}</td>
								<td>{{api.name}}</td>
								<td>{{api.project.name}}</td>
								<td>{{api.url}}</td>
								<td>{{api.get_method_display}}</td>
								<td>{{api.get_data_type_display}}</td>
								<td>{{api.description}}</td>
								<td>
									<a href="#"><span class="glyphicon glyphicon-remove" data-toggle="modal" data-target="#delModal_{{api.id}}"></span></a>&nbsp;&nbsp;
                  <div id="delModal_{{api.id}}" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title">删除确认</h4>
                        </div>
                        <div class="modal-body">
                          <p>是否确认删除接口？</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
                          <a href="{% url 'api_del' api.id %}"><button type="button" class="btn btn-danger">删除</button></a>
                        </div>
                      </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                  </div><!-- /.modal -->
                  <a href="{% url 'api_update' api.id %}"><span class="glyphicon glyphicon-edit"></span></a>&nbsp;&nbsp;
                  <a href="#"><span class="glyphicon glyphicon-play" data-toggle="modal" data-target="#testModal"></span></a>
                  <script type="text/javascript">
                      function testApi(){
                          $.ajax({
                              type: "POST",
                              url: "{% url 'api_test' api.id %}" ,//url
                              data: $('#api_test_form').serialize(),
                              success: function (result) {
                                  $("#test_response").html(result);
                              },
                              error : function() {
                                  console.log(result);
                              }
                          });
                      }
                  </script>
                  <div id="testModal" class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title">测试接口</h4>
                        </div>
                        <div class="modal-body">
                            <form name="api_test_form" id="api_test_form" class="form-horizontal">
                              <div class="form-group">
                                  <label for="prj_id" class="col-sm-2 control-label">选择环境</label>
                                  <div class="col-sm-10">
                                      <select name="env_id" class="form-control">
                                          {% for env in env_list %}
                                          <option value="{{env.id}}">{{env.name}}</option>
                                          {% endfor %}
                                      </select>
                                  </div>
                              </div>
                              <pre id='test_response'>--- 响应结果 ---</pre>
                            </form>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-primary" onclick="testApi()">发送</button>
                        </div>
                      </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                  </div><!-- /.modal -->
								</td>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			<!-- END BORDERED TABLE -->
		</div>
	</div>
{% endblock %}

app/templates/api_update.html
{% extends "base.html" %}
{% block title %}添加接口{% endblock %}
{% block content %}
	<div class="row">
		<ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">主页</a></li>
		  <li><a href="{% url 'api_list' %}">接口</a></li>
		  <li>修改接口</li>
		</ol>
	</div>
	<div class="row">
		<div class="col-md-12">
			<!-- INPUTS -->
			<div class="panel">
				<div class="panel-heading">
					<h3 class="panel-title">修改接口</h3>
				</div>
				<div class="panel-body">
					<form name='api_detail_form' id='api_detail_form' class="form-horizontal" action='.' method="POST" >
						{% csrf_token %}

						<div class="form-group">
							<label for="name" class="col-sm-2 control-label">接口名称</label>
							<div class="col-sm-10">
								<div class="input-group">
									<input id="name" name="name" type="text" class="form-control" value="{{api.name}}">
									<span class="input-group-btn">
								    	<button class="btn btn-default" data-toggle="modal" data-target="#testModal" type="button">测试</button>
								    </span>
                                    <div id="testModal" class="modal fade" tabindex="-1" role="dialog">
                                      <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                          <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title">测试接口</h4>
                                          </div>
                                          <div class="modal-body">
                                            <div class="form-group">
												<label for="prj_id" class="col-sm-2 control-label">选择环境</label>
												<div class="col-sm-10">
													<select name="env_id" class="form-control">
														{% for env in env_list %}
														<option value="{{env.id}}">{{env.name}}</option>
														{% endfor %}
													</select>
												</div>
											</div>
											<pre id='test_response'>--- 响应结果 ---</pre>
                                          </div>
                                          <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" onclick="testAction()">发送</button>
                                          </div>
                                        </div><!-- /.modal-content -->
                                      </div><!-- /.modal-dialog -->
                                    </div><!-- /.modal -->
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="description" class="col-sm-2 control-label">接口描述</label>
							<div class="col-sm-10">
								<textarea id="description" name="description" class="form-control" rows="3" style="resize: none;">{{api.description}}</textarea>
							</div>
						</div>
						<div class="form-group">
							<label for="prj_id" class="col-sm-2 control-label">项目名称</label>
							<div class="col-sm-10">
								<select name="prj_id" class="form-control">
									{% for prj in prj_list %}
									<option value="{{prj.id}}" {% if api.project == prj %}selected="selected"{% endif%}>{{prj.name}}</option>
									{% endfor %}
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="url" class="col-sm-2 control-label">接口Url</label>
							<div class="col-sm-8" style="padding-right: 0">
								<input id="url" name="url" type="text" class="form-control" value="{{api.url}}">
							</div>
							<div class="col-sm-2" style="padding-left: 0">
						      	<select name="method" class="form-control">
						      		<option value="1" {% if api.method == 1 %}selected="selected"{% endif%}>POST</option>
						      		<option value="2" {% if api.method == 2 %}selected="selected"{% endif%}>GET</option>
						      	</select>
							</div>
						</div>
						<div class="form-group form-inline">
							<label for="data_type" class="col-sm-2 control-label">数据类型</label>
							<div class="col-sm-10">
								<label style="padding-right: 20px">
									<input name="data_type" value="1" {% if api.data_type == 1 %}checked="checked"{% endif%} type="radio">
									<span>JSON</span>
								</label>
								<label style="padding-right: 20px">
									<input name="data_type" value="2" {% if api.data_type == 2 %}checked="checked"{% endif%} type="radio">
									<span>FORM</span>
								</label>
								<label>
									<input name="data_type" value="3" {% if api.data_type == 3 %}checked="checked"{% endif%} type="radio">
									<span>XML</span>
								</label>
							</div>
						</div>
						<div class="form-group">
							<label for="request_body" class="col-sm-2 control-label">请求数据</label>
							<div class="col-sm-10">
								<textarea id="request_body" name="request_body" class="form-control" rows="5">{{api.request_body}}</textarea>
							</div>
						</div>
						<div class="form-group">
							<label for="request_body" class="col-sm-2 control-label">响应数据</label>
							<div class="col-sm-10">
								<textarea id="request_body" name="response_body" class="form-control" rows="5"></textarea>
							</div>
						</div>
						<div class="form-group form-inline">
						    <div class="col-sm-offset-2 col-sm-10">
							    <button type="submit" class="btn btn-default">保存</button>
						    </div>
						</div>
					</form>
				</div>
			</div>
			<!-- END INPUTS -->
		</div>
	</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
	function testAction(){
	    $.ajax({
            //几个参数需要注意一下
            type: "POST",//方法类型
            // dataType: "json",//预期服务器返回的数据类型
            url: "{% url 'api_test' %}" ,//url
            data: $('#api_detail_form').serialize(),
            success: function (result) {
            	$("#test_response").html(result);
            },
            error : function() {
                console.log(result);//打印服务端返回的数据(调试用)
            }
        });
	}
</script>
{% endblock %}

app/templates/case_list.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
	<div class="row">
		<ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">主页</a></li>
		  <li>用例</li>
		</ol>
	</div>
	<div class="row">
		<div class="col-md-12">
			<!-- BORDERED TABLE -->
			<div class="panel">
				<div class="panel-body">
					<form style="padding: 10px 0; ">
						<a href="{% url 'case_add' %}"><button type="button" class="btn btn-primary">添加用例</button></a>
					</form>
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>用例名称</th>
								<th>测试计划</th>
								<th>用例描述</th>
								<th>操作</th>
							</tr>
						</thead>
						<tbody>
							{% for case in case_list %}
							<tr>
								<td>{{case.id}}</td>
								<td>{{case.name}}</td>
                                <td>{{case.plan}}</td>
								<td>{{case.description}}</td>
								<td>
									<a href="#"><span class="glyphicon glyphicon-remove" data-toggle="modal" data-target="#delModal_{{case.id}}"></span></a>&nbsp;&nbsp;
                      <div id="delModal_{{case.id}}" class="modal fade" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                              <h4 class="modal-title">删除确认</h4>
                            </div>
                            <div class="modal-body">
                              <p>是否确认删除用例？</p>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
                              <a href="{% url 'case_del' case.id %}"><button type="button" class="btn btn-danger">删除</button></a>
                            </div>
                          </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                      </div><!-- /.modal -->
                      <a href="{% url 'case_update' case.id %}"><span class="glyphicon glyphicon-edit"></span></a>&nbsp;&nbsp;
                      <!-- <a href="#"><span class="glyphicon glyphicon-play" data-toggle="modal" data-target="#testModal"></span></a> -->
                        <script type="text/javascript">
                            function testApi(){
                                $.ajax({
                                    type: "POST",
                                    url: "#" ,//url
                                    data: $('#api_test_form').serialize(),
                                    success: function (result) {
                                        $("#test_response").html(result);
                                    },
                                    error : function() {
                                        console.log(result);
                                    }
                                });
                            }
                        </script>
                        <div id="testModal" class="modal fade" tabindex="-1" role="dialog">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">测试接口</h4>
                              </div>
                              <div class="modal-body">
                                  <form name="api_test_form" id="api_test_form" class="form-horizontal">
                                    <div class="form-group">
                                        <label for="prj_id" class="col-sm-2 control-label">选择环境</label>
                                        <div class="col-sm-10">
                                            <select name="env_id" class="form-control">
                                                {% for env in env_list %}
                                                <option value="{{env.id}}">{{env.name}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <pre id='test_response'>--- 测试结果 ---</pre>
                                  </form>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-primary" onclick="testApi()">测试</button>
                              </div>
                            </div><!-- /.modal-content -->
                          </div><!-- /.modal-dialog -->
                      </div><!-- /.modal -->
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			<!-- END BORDERED TABLE -->
		</div>
	</div>
{% endblock %}

app/templates/sign_list.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
	<div class="row">
		<ol class="breadcrumb">
		  <li><a href="{% url 'index' %}">主页</a></li>
		  <li>签名</li>
		</ol>
	</div>
	<div class="row">
		<div class="col-md-12">
			<!-- BORDERED TABLE -->
			<div class="panel">
				<div class="panel-body">
					<br>
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>ID</th>
								<th>签名名称</th>
								<th>签名描述</th>
								<th>操作</th>
							</tr>
						</thead>
						<tbody>
							{% for sign in sign_list %}
							<tr>
								<td>{{sign.id}}</td>
								<td>{{sign.name}}</td>
								<td>{{sign.description}}</td>
								<td>
                                    <a href="{% url 'sign_detail' sign.id %}"><span class="glyphicon glyphicon-option-horizontal"></span></a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
			<!-- END BORDERED TABLE -->
		</div>
	</div>
{% endblock %}